version: '3.8'

services:
  gin-rest-api:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5